fos_user_security:
    resource: "@AppUserBundle/Controller/SecurityController.php"
    type:     annotation
    
fos_user_profile:
    resource: "@AppUserBundle/Controller/ProfileController.php"
    type:     annotation

fos_user_register:
    #resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    #prefix: /register
    resource: "@AppUserBundle/Controller/RegistrationController.php"
    type:     annotation

fos_user_resetting:
    #resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    #prefix: /resetting
    resource: "@AppUserBundle/Controller/ResettingController.php"
    type:     annotation

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile